SAAS-232: add anchore scan in circleci
Jahia/docker-jcustomer pull request #14
Opened 2020-09-29 10:55 UTC by Ronan-Gorain

2020-10-06 06:57 UTC, kevinvandel requested changes

2020-10-06 06:57 UTC, kevinvandel commented on .circleci/.anchore/policy_bundle.json
> +  "comment": "Comment for my default bundle",
Please replace placeholders with real values

2020-10-06 07:14 UTC, Ronan-Gorain commented on .circleci/.anchore/policy_bundle.json
> +  "comment": "Comment for my default bundle",
done

2020-10-09 11:37 UTC, kevinvandel approved these changes

2020-10-09 11:38 UTC, merged