BACKLOG-15558 Make jcustomer image wait for elasticsearch ready
Jahia/docker-jcustomer pull request #17
Opened 2021-02-15 16:04 UTC by hhocine

## JIRA

https://jira.jahia.org/browse/PROJECT-XXX

## Description

## Tests

The following are included in this PR
- [ ] Unit Tests (Most changes _should_ have unit tests)
- [ ] Integration Tests

## Checklist

I have considered the following implications of my change: 

- [ ] Security (in particular for changes to authentication, authorization, data fetching, ...)
- [ ] Performance
- [ ] Migration
- [ ] Code maintainability

## Documentation

- [ ] Inline documentation
- [ ] Internal Documentation (wiki)
- [ ] User-facing Documentation

2021-02-15 16:49 UTC, julian-maurel approved these changes

2021-02-16 15:16 UTC, laurentfufu requested changes

2021-02-16 15:16 UTC, laurentfufu commented on entrypoint.sh
> +    >&2 echo "Elastic Search is not yet available - waiting (health check=$health_check)..."
```suggestion
   echo "Elastic Search is not yet available - waiting (health check=$health_check)..."
```

2021-02-17 11:35 UTC, hhocine commented on entrypoint.sh
> +health_check="$(curl -fsSL "$UNOMI_ELASTICSEARCH_ADDRESSES/_cat/health?h=status")"
fixed

2021-02-17 11:35 UTC, hhocine commented on entrypoint.sh
> +    >&2 echo "Elastic Search is not yet available - waiting (health check=$health_check)..."
fixed

2021-02-18 08:36 UTC, laurentfufu approved these changes

2021-02-18 09:05 UTC, closed without merging